root = "."
testdata_dir = "testdata"
tmp_dir = "dist"

[build]
  args_bin = []
  bin = "./dist/main"
  cmd = "go build -o ./dist/main ./cmd/main.go"
  delay = 1000
  exclude_dir = ["assets", "dist", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["internal", "cmd", "schema"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_regex = ["internal/**"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
