version: "1.0.3"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - "app.env"
    volumes:
      - ddgf:/var/lib/postgresql/data
      
  cache:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    env_file:
      - "app.env"
    command: ["redis-server", "--requirepass ${REDIS_PASSWORD}"]

volumes:
  ddgf:
    driver: local
