version: "1.0.3"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ".env"
    volumes:
      - ddgf:/var/lib/postgresql/data
      
  cache:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

volumes:
  ddgf:
    driver: local
